In [3]:
#squared numbers in -50 to 51 range
quadr = [x**2 for x in range(-50,51)]
print(quadr)

[2500, 2401, 2304, 2209, 2116, 2025, 1936, 1849, 1764, 1681, 1600, 1521, 1444, 1369, 1296, 1225, 1156, 1089, 1024, 961, 900, 841, 784, 729, 676, 625, 576, 529, 484, 441, 400, 361, 324, 289, 256, 225, 196, 169, 144, 121, 100, 81, 64, 49, 36, 25, 16, 9, 4, 1, 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500]


In [9]:
div = [x/10 for x in range(1,10)]
print(div)

[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]


In [22]:
#Exercício 2.1
p = 0.05
n = 8
PA = [round(p*x,5) for x in range(0,n)]
print(PA)


[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35]


In [30]:
import math

In [5]:
#generate list with 25 random elements

import random as rd

n = 25
rand_num = [rd.randint(0,10) for _ in range(n)]
print(rand_num)
type(rand_num)

[4, 7, 2, 7, 5, 1, 8, 8, 10, 6, 10, 3, 5, 3, 5, 9, 5, 8, 5, 1, 2, 6, 2, 9, 0]


list

In [42]:
#squared numbers between -20 and 20. If the result is even, replace by -1.
l = [x**2 if (x**2)%2!=0 else -1 for x in range(-20,21)]
print(l)

[-1, 361, -1, 289, -1, 225, -1, 169, -1, 121, -1, 81, -1, 49, -1, 25, -1, 9, -1, 1, -1, 1, -1, 9, -1, 25, -1, 49, -1, 81, -1, 121, -1, 169, -1, 225, -1, 289, -1, 361, -1]


In [24]:
#Exercício 2.2
import random as rd
import math

n = 25
rand_num = [rd.randint(0,10) for _ in range(n)]
log = [round(math.log(n),1) if (n!=0.0) else math.nan for n in range(n)]
print(log)

[nan, 0.0, 0.7, 1.1, 1.4, 1.6, 1.8, 1.9, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.6, 2.7, 2.8, 2.8, 2.9, 2.9, 3.0, 3.0, 3.1, 3.1, 3.2]


In [67]:
math.log2(1)

0.0

In [68]:
vals1 = [5, 5, 5, 1, 2, 3, 4, 6, 7, 7]
vals2 = [5, 5, 5, 1, 2, 4, 4, 6, 6, 7]

equal_pos = [x if x == y else False for (x,y) in zip(vals1, vals2)]
print(equal_pos)

[5, 5, 5, 1, 2, False, 4, 6, False, 7]


In [1]:
#Exercício 2.3
import math
lista1 = [1,2,3,4,5]
lista2 = [1,2,3,4,5]
mult = [x*y if len(lista1) == len(lista2) else math.nan for (x,y) in zip(lista1, lista2)]
print(mult)

[1, 4, 9, 16, 25]


In [25]:
#Exercício 2.4
n = 4
linhas = [[(i+j*i) for j in range(n)] for i in range(n)]

for lin in linhas:
    print(lin)

[0, 0, 0, 0]
[1, 2, 3, 4]
[2, 4, 6, 8]
[3, 6, 9, 12]


In [ ]:
#Retornar erro:
if len (lista A) != len (lista B):
    print ('Tamanhos Diferentes')
    return nan
else: fórmula
    
#Transformar lista de string em int
inputs = ["1", "4", "10"]
for numero_s in inputs:
    numero_float = float (numero_s)
    print (numero_float + 1)

In [15]:
n = 10
linhas = [[1 if x == pos else 0 for x in range(n)] for pos in range(n)]

for lin in linhas:
    print(lin)

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


In [23]:
#Exercício 2.4 invertendo j e i
n = 4
linhas = [[(i+j*i) for i in range(n)] for j in range(n)]

for lin in linhas:
    print(lin)

[0, 1, 2, 3]
[0, 2, 4, 6]
[0, 3, 6, 9]
[0, 4, 8, 12]


In [26]:
cientistas_da_computacao = ['Betty Holberton', 'Alan Turing', 'Dennis Ritchie', 'Grace Hopper']

_ = [print(i) for i in cientistas_da_computacao]

Betty Holberton
Alan Turing
Dennis Ritchie
Grace Hopper


In [27]:
help(cientistas_da_computacao.sort)

Help on built-in function sort:

sort(*, key=None, reverse=False) method of builtins.list instance
    Sort the list in ascending order and return None.
    
    The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
    order of two equal elements is maintained).
    
    If a key function is given, apply it once to each list item and sort them,
    ascending or descending, according to their function values.
    
    The reverse flag can be set to sort in descending order.



In [33]:
# usando como chave o tamanho
cientistas_da_computacao.sort(key=len)
print(cientistas_da_computacao)
print(cientistas_da_computacao[0].split())
print(cientistas_da_computacao[2].split()[-1].lower())
cientistas_da_computacao.sort(key = lambda nome: nome.split()[-1].lower())
print(cientistas_da_computacao)

['Alan Turing', 'Grace Hopper', 'Dennis Ritchie', 'Betty Holberton']
['Alan', 'Turing']
ritchie
['Betty Holberton', 'Grace Hopper', 'Dennis Ritchie', 'Alan Turing']


In [64]:
cientistas_ABNT = ['Betty Holberton', 'Alan Turing', 'Dennis Ritchie', 'Grace Hopper']
print(cientistas_ABNT[3].split()[-1].upper(),' ,',cientistas_ABNT[3][0].upper(),'.')

HOPPER  , G .


In [50]:
print(cientistas_ABNT[1])

Alan Turing


In [61]:
print(cientistas_da_computacao[2].split())

['Dennis', 'Ritchie']


In [ ]:
nome = input("Digite seu nome e último sobrenome: ")
print(nome.split()[-1].upper(),' ,',nome[0][0].upper(),'.')

In [4]:
f = lambda nome: nome.split()[-1].upper()+', '+nome.split()[0][0]+'.'
f('Dharana Grassi')

'GRASSI, D.'

In [15]:
cientistas_ABNT = ['Betty Holberton', 'Alan Turing', 'Dennis Ritchie', 'Grace Hopper']
for n in cientistas_ABNT:
    print(cientistas_ABNT[2].split()[-1].upper(),' ,',cientistas_ABNT[1][0].upper(),'.')

RITCHIE  , A .
RITCHIE  , A .
RITCHIE  , A .
RITCHIE  , A .


In [14]:
for n in cientistas_ABNT:
    print (cientistas_ABNT[n])

TypeError: list indices must be integers or slices, not str

In [1]:
#Exercício 2.6
l_tup = [('a',[8, 4, 6, 1]), ('b',[1, 2, 3, 4]), ('c',[5, 3, 3, 3])]
print (l_tup)

[('a', [8, 4, 6, 1]), ('b', [1, 2, 3, 4]), ('c', [5, 3, 3, 3])]


In [23]:
import numpy as np

arr = np.array([el[1] for el in l_tup])
print (arr)


[[8 4 6 1]
 [1 2 3 4]
 [5 3 3 3]]


In [24]:
#Só as letras:
arr = np.array([el[0] for el in l_tup])
print (arr)

['a' 'b' 'c']


In [20]:
for l in arr:
    print(l[-3:])

[4 6 1]
[2 3 4]
[3 3 3]


In [23]:
#Exercício 2.7
import numpy as np
x = np.random.randint(1,5,60).reshape(6,10)
print (x)


[[1 1 2 1 3 1 2 1 1 4]
 [1 2 3 2 1 1 4 2 3 4]
 [4 4 2 1 3 4 2 4 2 1]
 [4 2 3 1 2 4 3 4 3 4]
 [1 1 1 3 4 4 3 1 2 3]
 [1 1 2 1 4 2 2 1 4 1]]


In [12]:
print(x[2:6,[2,5,8]])

[[2 4 4]
 [4 1 4]
 [3 3 4]
 [2 3 4]]


In [15]:
z = np.copy(x[2:6,[2,5,8]])
print (z)

[[2 4 4]
 [4 1 4]
 [3 3 4]
 [2 3 4]]


In [21]:
mask1 = (z>=4)
print (mask1)
print(z[mask1])

[[False  True  True]
 [ True False  True]
 [False False  True]
 [False False  True]]
[4 4 4 4 4 4]


In [17]:
# calculando uma máscara booleana onde o valor True 
# corresponde aos elementos maiores que 7
mask = (x > 7)
print('\nMascara booleana da matriz para valores maiores que 7')
print(mask)print('\nRecuperando apenas os elementos maiores que 7')
print(x[mask])

SyntaxError: invalid syntax (<ipython-input-17-ec90fee9aa68>, line 5)

In [24]:

print(x)
print('\nModificando apenas os elementos maiores que 7')
x[mask] = -1
print(x)

print('Filtrando pela negacao da mascara')
# filtrando e atribuindo a novo array elementos menores ou iguais a 7
y = x[~mask]
print(y)

[[1 1 2 1 3 1 2 1 1 4]
 [1 2 3 2 1 1 4 2 3 4]
 [4 4 2 1 3 4 2 4 2 1]
 [4 2 3 1 2 4 3 4 3 4]
 [1 1 1 3 4 4 3 1 2 3]
 [1 1 2 1 4 2 2 1 4 1]]

Modificando apenas os elementos maiores que 7


NameError: name 'mask' is not defined

In [43]:
#Exercício 2.9
import pandas as pd
dados = pd.read_csv (r'C:\Users\d016734\Downloads\tips.csv')
dados

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
240       29.03  5.92    Male     No   Sat  Dinner     3
241       27.18   NaN  Female    Yes   Sat  Dinner     2
242       22.67   NaN    Male    Yes   Sat  Dinner     2
243       17.82  1.75    Male     No   Sat  Dinner     2
244         NaN  3.00  Female     No  Thur  Dinner     2

[245 rows x 7 columns]

In [36]:
dados.loc[ (dados['time']=='Dinner') & (dados['total_bill']>=40), ['total_bill','size','tip']]

total_bill  size    tip
59        48.27     4   6.73
95        40.17     4   4.73
102       44.30     3   2.50
156       48.17     6   5.00
170       50.81     3  10.00
182       45.35     3   3.50
184       40.55     2   3.00
211       48.33     4   9.00

In [40]:
tips = dados.groupby(['day','time'])[['tip']].agg([np.mean, np.max])
tips

tip       
                 mean   amax
day  time                   
Fri  Dinner  2.940000   4.73
     Lunch   2.282500   3.48
Sat  Dinner  3.019647  10.00
Sun  Dinner  3.255132   6.50
Thur Dinner  3.000000   3.00
     Lunch   2.780500   6.70

In [ ]:
#Exercício 10